- name : Configure Docker on ubuntu Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io
    become : yes
    become_user : root

  - name : Start Docker Service
    command : sudo service docker start
    become : yes
    become_user : root

  - name: Deploy Docker Container
    command: docker run -itd -p 8083:8082 geethgulabrathod/health-care:1.0
